spring:
  jpa:
    hibernate:
      ddl-auto: update     
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        format-sql: true
        type.descriptor.sql.BasicBinder: TRACE          
  datasource:
    url: jdbc:mysql://localhost:6033/rabit?useSSL=false
    username: rabit
    password: rabit

config.oauth2.publicKey: |
      -----BEGIN PUBLIC KEY-----
      MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
      b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
      /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
      hL9dSAZuA8xExjlPmQIDAQAB
      -----END PUBLIC KEY-----
      
logging.level:
  org.springframework:
    security: debug
    boot: debug
  org.hibernate:
    type: TRACE
  com.cyhee:
    rabit: debug